### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayFramework#24]
When doing a clone from the project and running the tests as they are, there is one failing

 `ERROR: test_inject (tests.common.test_injector.TestInjector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bramV\Documents\PycharmProjects\WavesGatewayFrameworkQuart\tests\common\test_injector.py", line 53, in test_inject
    other_class_with_deps_instance = self._global_injector.get(other_class_with_deps_token)
  File "C:\Users\bramV\Documents\PycharmProjects\WavesGatewayFrameworkQuart\waves_gateway\common\injector.py", line 114, in get
    if self._dependency_map[token].instance is not None:
AttributeError: 'NoneType' object has no attribute 'instance'
`

**Comment by henning96** [comment]
Hello @BlackTurtle123,

I cannot confirm that. I did a clean install on my machine and the tests are still working. Are you using Python 3.5?

**Comment by BlackTurtle123** [comment]
I am using Python 3.7

**Comment by henning96** [comment]
I'm sorry, but we only support Python 3.5.

Bram N. <notifications@github.com> schrieb am Di., 25. Juni 2019, 08:48:

**Comment by BlackTurtle123** [comment]
Ow okay, the git makes it sound like it's recommended to have python3.5, but not fixed on python3.5, so that was why I was thinking at least 3.5
My bad then
